#!/usr/bin/env python3
"""
Generates the deployable contracts from their templates.

    concordat_appeal.py                       (hand-written leaf)
        |  embedded as base64 into
        v
    templates/concordat_case.tpl.py  ->  contracts/concordat_case.py
        |  embedded as base64 into
        v
    templates/concordat_hall.tpl.py  ->  contracts/concordat_hall.py

Only contracts/concordat_hall.py has to be deployed by hand; the hall
deploys cases, and each case deploys its own appeal contract.

Usage:
    python3 scripts/build.py           write the generated files
    python3 scripts/build.py --check   exit 1 if they are out of date
"""

import base64
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
TEMPLATES = ROOT / "templates"

APPEAL_PATH = CONTRACTS / "concordat_appeal.py"
CASE_TEMPLATE = TEMPLATES / "concordat_case.tpl.py"
CASE_PATH = CONTRACTS / "concordat_case.py"
HALL_TEMPLATE = TEMPLATES / "concordat_hall.tpl.py"
HALL_PATH = CONTRACTS / "concordat_hall.py"

LINE_WIDTH = 96


def _embed_block(name: str, source: str) -> str:
    var = "_%s_B64" % name.upper()
    encoded = base64.b64encode(source.encode("utf-8")).decode("ascii")
    chunks = [encoded[i : i + LINE_WIDTH] for i in range(0, len(encoded), LINE_WIDTH)]
    body = "\n".join('    "%s"' % chunk for chunk in chunks)
    return (
        "# @@BEGIN_EMBED %s@@\n"
        "# Generated by scripts/build.py from the %s contract source. Do not edit.\n"
        "%s = (\n%s\n)\n"
        "# @@END_EMBED %s@@"
    ) % (name, name, var, body, name)


def _render(template_path: Path, name: str, child_source: str) -> str:
    template = template_path.read_text(encoding="utf-8")
    pattern = re.compile(
        r"# @@BEGIN_EMBED %s@@\n.*?# @@END_EMBED %s@@" % (name, name), re.DOTALL
    )
    if len(pattern.findall(template)) != 1:
        raise SystemExit("%s must contain exactly one %s embed block" % (template_path, name))
    # A function replacement avoids any backslash interpretation.
    return pattern.sub(lambda _m: _embed_block(name, child_source), template)


def build_all() -> dict:
    """Return {path: content} for every generated file, in dependency order."""
    appeal_source = APPEAL_PATH.read_text(encoding="utf-8")
    case_source = _render(CASE_TEMPLATE, "appeal", appeal_source)
    hall_source = _render(HALL_TEMPLATE, "case", case_source)
    return {CASE_PATH: case_source, HALL_PATH: hall_source}


def main() -> int:
    generated = build_all()
    if "--check" in sys.argv:
        stale = [
            str(path.relative_to(ROOT))
            for path, content in generated.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("out of date: " + ", ".join(stale))
            print("run: python3 scripts/build.py")
            return 1
        print("generated contracts are up to date")
        return 0
    for path, content in generated.items():
        path.write_text(content, encoding="utf-8")
        print("wrote %s (%d bytes)" % (path.relative_to(ROOT), len(content.encode("utf-8"))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
